import gmsh
import sys

# # 1. Initialize Gmsh
# gmsh.initialize()

# # 2. Open the STEP file generated by build123d
# # Gmsh automatically interprets STEP boundaries for meshing
# gmsh.model.occ.importShapes("my_geometry.step")
# gmsh.model.occ.synchronize()

# # 3. Generate the 3D mesh (-3 for volumetric elements)
# gmsh.model.mesh.generate(3)

# # 4. Save to a Gmsh .msh file (or extract tags and nodes directly)
# gmsh.write("my_geometry.msh")

# # Optional: View the mesh visually
# if "nogui" not in sys.argv:
#     gmsh.fltk.run()

# # 5. Finalize the Gmsh environment
# gmsh.finalize()


def generate_mesh(filename: str):

    filename_without_extension = filename.rsplit(".", 1)[0]
    mesh_filename = f"{filename_without_extension}.msh"
    gmsh.initialize()
    gmsh.option.setNumber("General.Terminal", 0)
    gmsh.model.occ.importShapes(filename)
    gmsh.model.occ.synchronize()
    gmsh.model.mesh.generate(3)
    gmsh.write(mesh_filename)
    if "nogui" not in sys.argv:
        gmsh.fltk.run()
    gmsh.finalize()
